// <auto-generated />
using System;
using IDMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IDMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317063500_dropKolomCode")]
    partial class dropKolomCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IDMS.Shared.Domain.Entities.MstStocks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("deleted_by");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("harga");

                    b.Property<int>("JumlahStock")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah_stock");

                    b.Property<int>("Model_Id")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("mst_stock_pkey");

                    b.HasIndex("Model_Id");

                    b.ToTable("mst_stock", null, t =>
                        {
                            t.HasCheckConstraint("CK_mst_stock_harga_non_negative", "\"harga\" >= 0");

                            t.HasCheckConstraint("CK_mst_stock_jumlah_stock_non_negative", "\"jumlah_stock\" >= 0");
                        });
                });            
        
            modelBuilder.Entity("IDMS.Shared.Domain.Entities.MstStocks", b =>
                {
                    b.HasOne("IDMS.Shared.Domain.Entities.MstModels", "Models")
                        .WithMany()
                        .HasForeignKey("Model_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mst_stock_model_id_fky");

                    b.Navigation("Models");
                });

            
#pragma warning restore 612, 618
        }
    }
}
